Repository aqua-organisation/ah-django-Aqua, pull requests merged in 2019-03, with the labels that each got.

#3 #164691202 Unit tests for existing functionality
  .coveragerc
  .gitignore
  .travis.yml
  README.md
  authors/apps/authentication/migrations/0001_initial.py
  authors/apps/authentication/tests.py
  authors/apps/authentication/urls.py
  authors/settings.py
  authors/urls.py
  requirements.txt
Labels: Ready for Review, blocked

#4 #164691210 Configure Authors Haven to use PostgreSQL as DB Engine
  .travis.yml
  authors/settings.py
  env.example
  requirements.txt
Labels: Ready for Review, To be Merged

#9 #164691214 Implement JWT Token based authentication
  authors/apps/authentication/backends.py
  authors/apps/authentication/models.py
  authors/apps/authentication/renderers.py
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests.py
  authors/apps/authentication/views.py
  authors/settings.py
Labels: Ready for Review

#8 #164691211 Setup and deploy base application to Heroku
  Procfile
  authors/settings.py
  requirements.txt
Labels: Ready for Review

#7 #164691212 Integrate coveralls for test coverage reporting
  .travis.yml
  README.md
  requirements.txt
Labels: Ready for Review
